FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./

RUN python -m pip install --upgrade pip  setuptools==83.0.0\
    && python -m pip install -r requirements-dev.txt

COPY backend ./backend

CMD ["python", "-m", "pytest", "-v"]