name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    
jobs:
  tests:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - homeops
      - lxc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Python versoin
        run:  |
          python3 --version
          which pithon3

      - name: Create virtual enviroment
        run:  |
          python3 -m venv .venv-ci

      - name: Install dependencies
        run:  |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt

      - name: Run tests
        run:  |
          python -m pytest -v  