name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    
jobs:
  tests:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - homeops
      - lxc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Docker version
        run:  |
          docker --version

      - name: Build test image
        run:  |
          docker build -f Dockerfile.test -t homeops-test:${{ github.sha }} .

      - name: Run tests in container
        run:  |
          docker run --rm homeops-test:${{ github.sha }} 

      - name: Cleanup test image
        if: always()
        run:  |
          docker image rm homeops-test:${{ github.sha }} || true